import '@/styles/reset.css';
import '@/styles/global.scss';

import type { Metadata } from 'next';
import { Arimo } from 'next/font/google';
import Image from 'next/image';

import { Header } from '@/components/Header';

const arimo = Arimo({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
};

export const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='ru'>
    <body className={arimo.className}>
      <Header />
      <main className='main'>
        <div className='container'>{children}</div>
      </main>
      <div className='decor'>
        <Image
          alt='planet'
          height={620}
          quality={95}
          src='/planet.png'
          style={{ objectFit: 'contain' }}
          width={535}
        />
      </div>
    </body>
  </html>
);

export default RootLayout;
